using System.Text.Json.Serialization;

namespace EGovPay.Models.Transactions;

/// <summary>
/// Request body for the Generate Payment endpoint (<c>POST /api/v1/transaction</c>).
/// Field names and required-ness match the eGovPay API docs' Body Parameters table.
/// <c>digest</c> is not exposed here — <see cref="Services.TransactionService"/> computes
/// it for you from <see cref="Amount"/>, <see cref="TxnId"/>, and the client's API token.
/// </summary>
public sealed class TransactionCreateOptions
{
    /// <summary>Required. The transaction ID generated by the biller (your own reference number).</summary>
    [JsonPropertyName("txnid")]
    public required string TxnId { get; init; }

    /// <summary>Required. Line items making up the transaction.</summary>
    [JsonPropertyName("items")]
    public required List<TransactionItem> Items { get; init; }

    /// <summary>Required. The settlement template to use for bank settlements (see the merchant portal's Settlement Templates page).</summary>
    [JsonPropertyName("settlement_template_uuid")]
    public required string SettlementTemplateUuid { get; init; }

    /// <summary>Required. URL to redirect the payer to once the payment has been processed.</summary>
    [JsonPropertyName("redirect_url")]
    public required string RedirectUrl { get; init; }

    /// <summary>Required. Callback URL that will be notified for every transaction event.</summary>
    [JsonPropertyName("callback_url")]
    public required string CallbackUrl { get; init; }

    /// <summary>ISO 4217 currency code. Defaults to "PHP".</summary>
    [JsonPropertyName("currency")]
    public string Currency { get; init; } = "PHP";

    /// <summary>Mobile number of the customer, used for the e-receipt.</summary>
    [JsonPropertyName("mobile")]
    public string? Mobile { get; init; }

    /// <summary>Email of the customer.</summary>
    [JsonPropertyName("email")]
    public string? Email { get; init; }

    /// <summary>Name of the customer/payer.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; init; }

    /// <summary>Expiration of the transaction. Format: "YYYY-MM-DD HH:MM:SS".</summary>
    [JsonPropertyName("expires_at")]
    public string? ExpiresAt { get; init; }

    /// <summary>Expiration of the generated payment link. Format: "YYYY-MM-DD HH:MM:SS".</summary>
    [JsonPropertyName("link_expires_at")]
    public string? LinkExpiresAt { get; init; }

    /// <summary>Additional information attached to the transaction.</summary>
    [JsonPropertyName("description")]
    public Dictionary<string, object>? Description { get; init; }
}
